# -*- coding: utf-8 -*-
"""codeAlpha_Hangman Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBeIIj5KINHVfrxSiXaZ-z7WzArj2G-K
"""

import random

words = ["apple", "python", "coding", "hello", "computer"]

word = random.choice(words)

guesses = ""
chances = 6

print("Welcome to Hangman!")

while chances > 0:

    display = ""

    for letter in word:
        if letter in guesses:
            display = display + letter
        else:
            display = display + "_"

    print("Word:", display)

    if display == word:
        print("You won! 🎉")
        break

    guess = input("Guess a letter: ")

    if guess in guesses:
        print("You already guessed that letter!")
        continue

    guesses = guesses + guess

    if guess in word:
        print("Correct!")
    else:
        chances = chances - 1
        print("Wrong!")
        print("Chances left:", chances)

if chances == 0:
    print("Game Over!")
    print("The word was:", word)